export default [{
  title: "文档目录",
  link: "",
  children: [
    {
      title: "萌新必读",
      link: "",
      children: [
        {
          title: "简介",
          link: "/intro/", children: []
          
        },
        { title: "交流群", link: "/qun/", children: [] },
        { title: "视频教程", link: "/video/", children: [] },
        { title: "功能列表", link: "/feature/", children: [] },
        { title: "快速启动（后端项目）", link: "/quick-start/", children: [] },
        {
          title: "快速启动（前端项目）",
          link: "/quick-start-front/",
          children: [],
        },
        { title: "接口文档", link: "/api-doc/", children: [] },
        { title: "技术选型", link: "/technology/", children: [] },
        { title: "项目结构", link: "/project-intro/", children: [] },
        { title: "代码热加载", link: "/dev-hot-swap/", children: [] },
        { title: "一键改包", link: "/project-rename/", children: [] },
        {
          title: "迁移模块（适合新项目）",
          link: "/migrate-module/",
          children: [],
        },
        {
          title: "删除功能（以租户为例）",
          link: "/delete-code/",
          children: [],
        },
        { title: "表结构变更（版本升级）", link: "/sql-update/", children: [] },
        {
          title: "国产信创数据库（DM 达梦、大金、OpenGauss）",
          link: "/xinchuang-db/",
          children: [],
        },
        { title: "内网穿透", link: "/natapp/", children: [] },
        {
          title: "面试题、简历模版、简历优化",
          link: "/interview/",
          children: [],
        },
      ],
    },
    {
      title: "后端手册",
      link: "",
      children: [
        { title: "新建模块", link: "/module-new/", children: [] },
        {
          title: "代码生成【单表】（新增功能）",
          link: "/new-feature/",
          children: [],
        },
        {
          title: "代码生成【主子表】",
          link: "/new-feature/master-sub/",
          children: [],
        },
        { title: "代码生成（树表）", link: "/new-feature/tree/", children: [] },
        { title: "功能权限", link: "/resource-permission/", children: [] },
        { title: "数据权限", link: "/data-permission/", children: [] },
        { title: "用户体系", link: "/user-center/", children: [] },
        { title: "三方登录", link: "/social-user/", children: [] },
        { title: "OAuth 2.0（SSO 单点登录）", link: "/oauth2/", children: [] },
        {
          title: "SaaS 多租户【字段隔离】",
          link: "/saas-tenant/",
          children: [],
        },
        {
          title: "SaaS 多租户【数据库隔离】",
          link: "/saas-tenant/dynamic/",
          children: [],
        },
        { title: "WebSocket 实时通信", link: "/websocket/", children: [] },
        { title: "异常处理（错误码）", link: "/exception/", children: [] },
        { title: "参数校验、时间传参", link: "/validator/", children: [] },
        { title: "分页实现", link: "/page-feature/", children: [] },
        { title: "VO 对象转换、数据翻译", link: "/vo/", children: [] },
        { title: "文件存储（上传下载）", link: "/file/", children: [] },
        {
          title: "Excel 导入导出",
          link: "/excel-import-and-export/",
          children: [],
        },
        {
          title: "操作日志、访问日志、异常日志",
          link: "/system-log/",
          children: [],
        },
        { title: "MyBatis 数据库", link: "/mybatis/", children: [] },
        { title: "MyBatis 联表&分页查询", link: "/mybatis-pro/", children: [] },
        {
          title: "多数据源（读写分离）、事务",
          link: "/dynamic-datasource/",
          children: [],
        },
        { title: "Redis 缓存", link: "/redis-cache/", children: [] },
        { title: "本地缓存", link: "/local-cache/", children: [] },
        { title: "异步任务", link: "/async-task/", children: [] },
        { title: "分布式锁", link: "/distributed-lock/", children: [] },
        { title: "幂等性（防重复提交）", link: "/idempotent/", children: [] },
        {
          title: "请求限流（RateLimiter）",
          link: "/rate-limiter/",
          children: [],
        },
        { title: "HTTP 接口签名（防篡改）", link: "/http-sign/", children: [] },
        { title: "单元测试", link: "/unit-test/", children: [] },
        { title: "验证码", link: "/captcha/", children: [] },
        { title: "工具类 Util", link: "/util/", children: [] },
        { title: "配置管理", link: "/config-center/", children: [] },
        { title: "数据库文档", link: "/db-doc/", children: [] },
      ],
    },
    {
      title: "中间件手册",
      link: "",
      children: [
        { title: "定时任务", link: "/job/", children: [] },
        {
          title: "消息队列（内存）",
          link: "/message-queue/event/",
          children: [],
        },
        {
          title: "消息队列（Redis）",
          link: "/message-queue/redis/",
          children: [],
        },
        {
          title: "消息队列（RocketMQ）",
          link: "/message-queue/rocketmq/",
          children: [],
        },
        {
          title: "消息队列（RabbitMQ）",
          link: "/message-queue/rabbitmq/",
          children: [],
        },
        {
          title: "消息队列（Kafka）",
          link: "/message-queue/kafka/",
          children: [],
        },
        { title: "限流熔断", link: "/server-protection/", children: [] },
      ],
    },
    {
      title: "工作流手册",
      link: "",
      children: [
        { title: "工作流演示", link: "/bpm-preview/", children: [] },
        { title: "功能开启", link: "/bpm/", children: [] },
        { title: "工作流（达梦适配）", link: "/bpm/dameng/", children: [] },
        {
          title: "审批接入（流程表单）",
          link: "/bpm/use-bpm-form/",
          children: [],
        },
        {
          title: "审批接入（业务表单）",
          link: "/bpm/use-business-form/",
          children: [],
        },
        {
          title: "流程设计器（BPMN）",
          link: "/bpm/model-designer-bpmn/",
          children: [],
        },
        {
          title: "流程设计器（钉钉、飞书）",
          link: "/bpm/model-designer-dingding/",
          children: [],
        },
        {
          title: "选择审批人、发起人自选",
          link: "/bpm/assignee/",
          children: [],
        },
        {
          title: "会签、或签、依次审批",
          link: "/bpm/multi-instance/",
          children: [],
        },
        {
          title: "流程发起、取消、重新发起",
          link: "/bpm/process-instance/",
          children: [],
        },
        {
          title: "审批通过、不通过、驳回",
          link: "/bpm/task-todo-done/",
          children: [],
        },
        { title: "审批加签、减签", link: "/bpm/sign/", children: [] },
        {
          title: "审批转办、委派、抄送",
          link: "/bpm/task-delegation-and-cc/",
          children: [],
        },
        {
          title: "执行监听器、任务监听器",
          link: "/bpm/listener/",
          children: [],
        },
        { title: "流程表达式", link: "/bpm/expression/", children: [] },
        { title: "流程审批通知", link: "/bpm/message/", children: [] },
      ],
    },
    {
      title: "大屏手册",
      link: "",
      children: [
        { title: "报表设计器", link: "/report/", children: [] },
        { title: "大屏设计器", link: "/report/screen/", children: [] },
      ],
    },
    {
      title: "支付手册",
      link: "",
      children: [
        { title: "功能开启", link: "/pay/build/", children: [] },
        {
          title: "支付宝支付接入",
          link: "/pay/alipay-pay-demo/",
          children: [],
        },
        {
          title: "微信公众号支付接入",
          link: "/pay/wx-pub-pay-demo/",
          children: [],
        },
        {
          title: "微信小程序支付接入",
          link: "/pay/wx-lite-pay-demo/",
          children: [],
        },
        {
          title: "支付宝、微信退款接入",
          link: "/pay/refund-demo/",
          children: [],
        },
        { title: "钱包充值、支付、退款", link: "/pay/wallet/", children: [] },
        { title: "模拟支付、退款", link: "/pay/mock/", children: [] },
      ],
    },
    {
      title: "会员手册",
      link: "",
      children: [
        { title: "功能开启", link: "/member/build/", children: [] },
        {
          title: "微信公众号登录",
          link: "/member/weixin-mp-login/",
          children: [],
        },
        {
          title: "微信小程序登录",
          link: "/member/weixin-lite-login/",
          children: [],
        },
        {
          title: "微信小程序订阅消息",
          link: "/member/weixin-lite-subscribe-message/",
          children: [],
        },
        {
          title: "微信小程序码",
          link: "/member/weixin-lite-qrcode/",
          children: [],
        },
        { title: "会员用户、标签、分组", link: "/member/user/", children: [] },
        { title: "会员等级、积分、签到", link: "/member/level/", children: [] },
      ],
    },
    {
      title: "商城手册",
      link: "",
      children: [
        { title: "商城演示", link: "/mall-preview/", children: [] },
        { title: "功能开启", link: "/mall/build/", children: [] },
        { title: "商城装修", link: "/mall/diy/", children: [] },
        { title: "在线客服", link: "/mall/kefu/", children: [] },
        {
          title: "【商品】商品分类",
          link: "/mall/product-category/",
          children: [],
        },
        {
          title: "【商品】商品属性",
          link: "/mall/product-property/",
          children: [],
        },
        {
          title: "【商品】商品 SPU 与 SKU",
          link: "/mall/product-spu-sku/",
          children: [],
        },
        {
          title: "【商品】商品评价",
          link: "/mall/product-comment/",
          children: [],
        },
        { title: "【交易】购物车", link: "/mall/trade-cart/", children: [] },
        { title: "【交易】交易订单", link: "/mall/trade-order/", children: [] },
        {
          title: "【交易】售后退款",
          link: "/mall/trade-aftersale/",
          children: [],
        },
        {
          title: "【交易】快递发货",
          link: "/mall/trade-delivery-express/",
          children: [],
        },
        {
          title: "【交易】门店自提",
          link: "/mall/trade-delivery-pickup/",
          children: [],
        },
        {
          title: "【交易】分销返佣",
          link: "/mall/trade-brokerage/",
          children: [],
        },
        {
          title: "【营销】优惠劵",
          link: "/mall/promotion-coupon/",
          children: [],
        },
        {
          title: "【营销】拼团活动",
          link: "/mall/promotion-combination/",
          children: [],
        },
        {
          title: "【营销】秒杀活动",
          link: "/mall/promotion-seckill/",
          children: [],
        },
        {
          title: "【营销】砍价活动",
          link: "/mall/promotion-bargain/",
          children: [],
        },
        {
          title: "【营销】满减送",
          link: "/mall/promotion-record/",
          children: [],
        },
        {
          title: "【营销】限时折扣",
          link: "/mall/promotion-discount/",
          children: [],
        },
        {
          title: "【营销】内容管理",
          link: "/mall/promotion-content/",
          children: [],
        },
        {
          title: "【统计】会员、商品、交易统计",
          link: "/mall/statistics/",
          children: [],
        },
      ],
    },
    {
      title: "ERP手册",
      link: "",
      children: [
        { title: "ERP 演示", link: "/erp-preview/", children: [] },
        { title: "功能开启", link: "/erp/build/", children: [] },
        {
          title: "【产品】产品信息、分类、单位",
          link: "/erp/product/",
          children: [],
        },
        {
          title: "【库存】产品库存、库存明细",
          link: "/erp/stock/",
          children: [],
        },
        {
          title: "【库存】其它入库、其它出库",
          link: "/erp/stock-in-out/",
          children: [],
        },
        {
          title: "【库存】库存调拨、库存盘点",
          link: "/erp/stock-move-check/",
          children: [],
        },
        {
          title: "【采购】采购订单、入库、退货",
          link: "/erp/purchase/",
          children: [],
        },
        {
          title: "【销售】销售订单、出库、退货",
          link: "/erp/sale/",
          children: [],
        },
        {
          title: "【财务】采购付款、销售收款",
          link: "/sale/finance-payment-receipt/",
          children: [],
        },
      ],
    },
    {
      title: "CRM手册",
      link: "",
      children: [
        { title: "CRM 演示", link: "/crm-preview/", children: [] },
        { title: "功能开启", link: "/crm/build/", children: [] },
        { title: "【线索】线索管理", link: "/crm/clue/", children: [] },
        {
          title: "【客户】客户管理、公海客户",
          link: "/crm/customer/",
          children: [],
        },
        {
          title: "【商机】商机管理、商机状态",
          link: "/crm/business/",
          children: [],
        },
        {
          title: "【合同】合同管理、合同提醒",
          link: "/crm/contract/",
          children: [],
        },
        {
          title: "【回款】回款管理、回款计划",
          link: "/crm/receivable/",
          children: [],
        },
        {
          title: "【产品】产品管理、产品分类",
          link: "/crm/product/",
          children: [],
        },
        { title: "【通用】数据权限", link: "/crm/permission/", children: [] },
        {
          title: "【通用】跟进记录、待办事项",
          link: "/crm/follow-up/",
          children: [],
        },
      ],
    },
    {
      title: "AI大模型手册",
      link: "",
      children: [
        { title: "AI 大模型演示", link: "/ai-preview/", children: [] },
        { title: "功能开启", link: "/ai/build/", children: [] },
        { title: "AI 聊天对话", link: "/ai/chat/", children: [] },
        { title: "AI 绘画创作", link: "/ai/image/", children: [] },
        { title: "AI 音乐创作", link: "/ai/music/", children: [] },
        { title: "AI 写作助手", link: "/ai/write/", children: [] },
        { title: "AI 思维导图", link: "/ai/mindmap/", children: [] },
        { title: "【模型接入】OpenAI", link: "/ai/openai/", children: [] },
        { title: "【模型接入】通义千问", link: "/ai/tongyi/", children: [] },
        { title: "【模型接入】LLAMA", link: "/ai/llama/", children: [] },
        { title: "【模型接入】文心一言", link: "/ai/yiyan/", children: [] },
        { title: "【模型接入】DeepSeek", link: "/ai/deep-seek/", children: [] },
        { title: "【模型接入】智谱 GLM", link: "/ai/glm/", children: [] },
        { title: "【模型接入】讯飞星火", link: "/ai/xinghuo/", children: [] },
        {
          title: "【模型接入】微软 OpenAI",
          link: "/ai/azure-openai/",
          children: [],
        },
        { title: "【模型接入】谷歌 Gemini", link: "/ai/gemini/", children: [] },
        {
          title: "【模型接入】Stable Diffusion",
          link: "/ai/stable-diffusion/",
          children: [],
        },
        {
          title: "【模型接入】Midjourney",
          link: "/ai/midjourney/",
          children: [],
        },
        { title: "【模型接入】Suno", link: "/ai/suno/", children: [] },
      ],
    },
    {
      title: "公众号手册",
      link: "",
      children: [
        { title: "功能开启", link: "/mp/build/", children: [] },
        { title: "公众号接入", link: "/mp/account/", children: [] },
        { title: "公众号粉丝", link: "/mp/user/", children: [] },
        { title: "公众号标签", link: "/mp/tag/", children: [] },
        { title: "公众号消息", link: "/mp/message/", children: [] },
        { title: "自动回复", link: "/mp/auto-reply/", children: [] },
        { title: "公众号菜单", link: "/mp/menu/", children: [] },
        { title: "公众号素材", link: "/mp/material/", children: [] },
        { title: "公众号图文", link: "/mp/article/", children: [] },
        { title: "公众号统计", link: "/mp/statistics/", children: [] },
      ],
    },
    {
      title: "系统手册",
      link: "",
      children: [
        { title: "短信配置", link: "/sms/", children: [] },
        { title: "邮件配置", link: "/mail/", children: [] },
        { title: "站内信配置", link: "/notify/", children: [] },
        { title: "数据脱敏、字段权限", link: "/desensitize/", children: [] },
        { title: "敏感词", link: "/sensitive-word/", children: [] },
        { title: "地区 & IP 库", link: "/area-and-ip/", children: [] },
      ],
    },
    {
      title: "运维手册",
      link: "",
      children: [
        { title: "开发环境", link: "/dev-env/", children: [] },
        { title: "Linux 部署", link: "/deployment-linux/", children: [] },
        { title: "Docker 部署", link: "/deployment-docker/", children: [] },
        { title: "Jenkins 部署", link: "/deployment-jenkins/", children: [] },
        { title: "宝塔部署", link: "/deployment-baota/", children: [] },
        { title: "HTTPS 证书", link: "/https/", children: [] },
        { title: "服务监控", link: "/server-monitor/", children: [] },
      ],
    },
    {
      title: "前端手册 Vue 3.x",
      link: "",
      children: [
        { title: "开发规范", link: "/vue3/dev-spec/", children: [] },
        { title: "菜单路由", link: "/vue3/route/", children: [] },
        { title: "Icon 图标", link: "/vue3/icon/", children: [] },
        { title: "字典数据", link: "/vue3/dict/", children: [] },
        { title: "系统组件", link: "/vue3/components/", children: [] },
        { title: "通用方法", link: "/vue3/util/", children: [] },
        { title: "配置读取", link: "/vue3/config-center/", children: [] },
        { title: "CRUD 组件", link: "/vue3/crud-schema/", children: [] },
        { title: "国际化", link: "/vue3/i18n/", children: [] },
        { title: "IDE 调试", link: "/vue3/debugger/", children: [] },
        { title: "代码格式化", link: "/vue3/format/", children: [] },
      ],
    },
    {
      title: "前端手册 Vue 2.x",
      link: "",
      children: [
        { title: "开发规范", link: "/vue2/dev-spec/", children: [] },
        { title: "菜单路由", link: "/vue2/route/", children: [] },
        { title: "Icon 图标", link: "/vue2/icon/", children: [] },
        { title: "字典数据", link: "/vue2/dict/", children: [] },
        { title: "系统组件", link: "/vue2/components/", children: [] },
        { title: "通用方法", link: "/vue2/util/", children: [] },
        { title: "配置读取", link: "/vue2/config-center/", children: [] },
      ],
    },
    {
      title: "前端手册 Vue 2.x",
      link: "",
      children: [
        { title: "开发规范", link: "/vue2/dev-spec/", children: [] },
        { title: "菜单路由", link: "/vue2/route/", children: [] },
        { title: "Icon 图标", link: "/vue2/icon/", children: [] },
        { title: "字典数据", link: "/vue2/dict/", children: [] },
        { title: "系统组件", link: "/vue2/components/", children: [] },
        { title: "通用方法", link: "/vue2/util/", children: [] },
        { title: "配置读取", link: "/vue2/config-center/", children: [] },
      ],
    },
    {
      title: "更新日志",
      link: "",
      children: [
        
        {
          title: "【v2.2.0】2024-08-02",
          link: "/changelog/2.2.0/",
          children: [],
        },
        {
          title: "【v2.1.0】2024-05-05",
          link: "/changelog/2.1.0/",
          children: [],
        },
        {
          title: "【v2.0.1】2024-03-01",
          link: "/changelog/2.0.1/",
          children: [],
        },
        {
          title: "【v2.0.0】2024-01-26",
          link: "/changelog/2.0.0/",
          children: [],
        },
      ],
    },
  ],
}]